In [1]:
import pandas as pd

records = []

with open("MLFH041020180321.traversals.gaf") as f:
    for line in f:
        if line.startswith("@"):
            continue
        fields = line.strip().split("\t")

        name = fields[0]
        path = fields[5]
        length = int(fields[6])
        support = int(fields[12].split(":")[-1])

        parts = name.split("#")
        chrom = parts[2]
        pos = int(parts[3])
        snarl = parts[4]
        allele = int(parts[6])

        records.append({
            "chrom": chrom,
            "pos": pos,
            "snarl": snarl,
            "allele": allele,
            "length": length,
            "support": support,
            "path": path,
        })

df = pd.DataFrame(records)
df

/tmp/ipykernel_1168285/2542149856.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

,chrom,pos,snarl,allele,length,support,path
0,Chr1,426310,>28732>28810,0,10,3,>28732>28810
1,Chr1,426310,>28732>28810,1,239,0,>28732>28733>28734>28736>28738>28739>28740>287...
2,Chr1,426310,>28732>28810,2,239,0,>28732>28733>28734>28736>28738>28739>28740>287...
3,Chr1,426310,>28732>28810,3,239,0,>28732>28733>28734>28736>28738>28739>28740>287...
4,Chr1,426310,>28732>28810,4,239,0,>28732>28733>28734>28736>28738>28739>28740>287...
...,...,...,...,...,...,...,...
341948,Chr1,22771940,>1584746>2381118,46,3329,6,>1584746>1584747>1584749>1584750>1584752>15847...
341949,Chr1,22771940,>1584746>2381118,47,3329,6,>1584746>1584747>1584749>1584750>1584752>15847...
341950,Chr1,22771940,>1584746>2381118,48,3329,6,>1584746>1584747>1584749>1584750>1584752>15847...
341951,Chr1,22771940,>1584746>2381118,49,3329,6,>1584746>1584747>1584749>1584750>1584752>15847...
341952,Chr1,22771940,>1584746>2381118,50,3329,6,>1584746>1584747>1584749>1584750>1584752>15847...

In [3]:
df['chrom'].value_counts()

chrom
Chr5    84418
Chr1    82129
Chr3    61739
Chr2    59390
Chr4    54277
Name: count, dtype: int64

In [5]:
df['allele'].value_counts()

allele
0     18045
1     18045
2     12192
3     10093
4      9540
5      8630
6      8326
7      8061
8      7846
9      7294
10     7170
11     7054
12     6955
13     6813
14     6718
15     6644
16     6578
17     6248
18     6176
19     6103
20     6054
21     5996
22     5945
23     5907
24     5862
25     5796
26     5759
27     5735
28     5706
29     5667
30     5636
31     5621
32     5593
33     5345
34     5319
35     5298
36     5276
37     5253
38     5242
39     5233
40     5221
41     5199
42     5193
43     5184
44     5175
45     5171
46     5166
47     5158
48     5150
49     5093
50     3469
Name: count, dtype: int64

In [6]:
df

,chrom,pos,snarl,allele,length,support,path
0,Chr1,426310,>28732>28810,0,10,3,>28732>28810
1,Chr1,426310,>28732>28810,1,239,0,>28732>28733>28734>28736>28738>28739>28740>287...
2,Chr1,426310,>28732>28810,2,239,0,>28732>28733>28734>28736>28738>28739>28740>287...
3,Chr1,426310,>28732>28810,3,239,0,>28732>28733>28734>28736>28738>28739>28740>287...
4,Chr1,426310,>28732>28810,4,239,0,>28732>28733>28734>28736>28738>28739>28740>287...
...,...,...,...,...,...,...,...
341948,Chr1,22771940,>1584746>2381118,46,3329,6,>1584746>1584747>1584749>1584750>1584752>15847...
341949,Chr1,22771940,>1584746>2381118,47,3329,6,>1584746>1584747>1584749>1584750>1584752>15847...
341950,Chr1,22771940,>1584746>2381118,48,3329,6,>1584746>1584747>1584749>1584750>1584752>15847...
341951,Chr1,22771940,>1584746>2381118,49,3329,6,>1584746>1584747>1584749>1584750>1584752>15847...
341952,Chr1,22771940,>1584746>2381118,50,3329,6,>1584746>1584747>1584749>1584750>1584752>15847...

In [7]:
df.groupby(["chrom", "pos", "snarl"])